### ISSUE TITLE
Crash when year field is empty

### ISSUE THREAD

**Issue by yishn** [rubencodes/recal#2]
On the [demo page](https://rubencodes.github.io/recal/), if you empty the year input element on either of the calendars, the whole page breaks. I've tested on Chrome 65.

**Comment by rubencodes** [comment]
Good catch! I'll look into how this can be patched ASAP.

**Comment by rubencodes** [comment]
The issue is, as you might guess, an empty string year value is parseInt'd to NaN, which in turn results in an Invalid Date issue. 

I can think of a few possible solutions here:

1) Prevent the user from having a "year" value with less than one digit. 
- This is fine on desktop because modern browsers implement an up and down array which is easier to use anyway, but on mobile, it would likely prevent the user from entering a date like "1999", since they'd have to edit the first digit, without selecting the input value and typing over it. 
2) Default the year to "0" when there is no value.
- On the surface this seems like the solution with the least amount of ramifications. However it falls prey to a known React bug with leading 0's (see: https://github.com/facebook/react/issues/9402). However, what we could do is leave the input empty and treat it _is if_ it were 0.

After testing, it seems like solution 2 might be viable for release as a patch. I just have to make sure the code treats empty year as 0 everywhere.
